[package]
name = "multiudpled"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
lazy_static = "1.5.0"
dropshot = "0.15.1"
dashmap = "6.1.0"
chrono = "0.4.39"
colored = "2.2.0"